version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
      WORDPRESS_DB_NAME: ${MYSQL_DBNAME}
    volumes:
      - ${PWD}/src:/var/www/html

  db:
    image: mariadb:10.6
    container_name: wp-practice_db_1
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  theme-builder:
    build:
      context: .
      dockerfile: theme-builder/Dockerfile
    volumes:
      - ${PWD}/src/wp-content/themes/fictional-university-theme:/usr/src/app
      

volumes:
  db:
  wordpress:
